#!/usr/bin/env perl

$latex         = 'platex -shell-escape -synctex=1 -halt-on-error';
$latex_silent  = 'platex -shell-escape -synctex=1 -halt-on-error -interaction=batchmode';
$bibtex        = 'pbibtex %O %B';
$dvipdf        = 'dvipdfmx %O -f ptex-ipaex.map -o %D %S';
$makeindex     = 'mendex %O -o %D %S';
$max_repeat    = 5;
$pdf_mode      = 3;

$pvc_view_file_via_temporary = 0;

$pdf_previewer = 'xreader';

#$latex='platex -kanji=utf8 -guess-input-enc -syntex=1 -interaction=nonstopmode %S';
#$dvipdf='dvipdfmx %S -f ptex-ipaex.map';
#$bibtex='pbibtex -kanji=utf8 %B';

